version: '3.8'

services:
  app-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tests
      network: host
    environment:
      - DB__URL=postgresql://postgres:postgres@db:5432/app_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
